#pragma once

#include <cstdint>
#include <scry/error.hpp>
#include <scry/json.hpp>
#include <scry/turn_id.hpp>
#include <scry/unique_function.hpp>
#include <string>
#include <string_view>

namespace scry {

/// Provider-visible definition of a dynamic tool: one whose schema is written by
/// hand rather than generated by reflection.
struct ToolDefinition {
  /// Unique tool name exposed to the model.
  std::string name{};
  /// Human-readable description exposed to the model.
  std::string description{};
  /// JSON Schema object describing the tool's arguments.
  Json input_schema{};
};

/// Provider-visible name and description of a tool registered with
/// ToolRegistry::add<Args>(), whose schema reflection generates from `Args`.
struct ToolMetadata {
  /// Unique tool name exposed to the model.
  std::string name{};
  /// Human-readable description exposed to the model.
  std::string description{};
};

/// Identity of the tool call a handler is servicing.
///
/// A handler that needs to know which turn, round, or call it is running for takes
/// one of these as its leading parameter. Both string views are borrowed from the
/// live call block and are valid only for the duration of the invocation; a handler
/// that keeps either beyond its return must copy it.
struct ToolCallContext {
  /// Turn the call belongs to.
  TurnId turn_id{};
  /// Provider-assigned identifier of this call, matching ToolCall::id.
  std::string_view call_id{};
  /// Registered name of the tool being invoked.
  std::string_view tool_name{};
  /// One-based tool round within the turn.
  std::uint32_t round{};
  /// Zero-based position of this call in its round's batch.
  std::uint32_t index{};
};

/// Move-only type-erased dynamic tool handler.
///
/// The input is a canonical JSON object: Scry has checked that the arguments parse
/// and form an object, and nothing more. They are not checked against the registered
/// input_schema, because Scry does not perform general JSON Schema validation; the
/// handler owns that check, and returning scry::tool_error() tells the model what was
/// wrong so it can correct the call. A successful return must contain valid JSON.
/// Reflected tools, registered through ToolRegistry::add(), instead get a generated
/// decoder that enforces the schema it generates.
using ToolHandler = UniqueFunction<Result<Json>(Json)>;

/// Move-only type-erased dynamic tool handler that also receives its call identity.
///
/// Identical to ToolHandler apart from the leading ToolCallContext, whose string
/// views are borrowed for the invocation only.
using ContextualToolHandler =
    UniqueFunction<Result<Json>(const ToolCallContext&, Json)>;

namespace detail {

/// One tool on its way into a ToolRegistry, in the shape every registration
/// path lowers to. A reflected toolbox or namespace produces several at once,
/// and the registry inserts them together or not at all.
struct ToolEntry {
  /// Provider-visible contract.
  ToolDefinition definition{};
  /// Handler invoked with the call identity and canonical argument JSON.
  ContextualToolHandler handler{};
};

} // namespace detail

} // namespace scry
